In [130]:
from sklearn.linear_assignment_ import linear_assignment

ModuleNotFoundError: No module named 'sklearn.linear_assignment_'

In [ ]:
P

In [128]:
import torch

d = torch.randn((100, 15))
(d.unsqueeze(2) @ d.unsqueeze(1)).mean(dim=0)

tensor([[ 1.0214,  0.0063, -0.0042, -0.1425,  0.0659,  0.2898,  0.0491,  0.1660,
         -0.0318, -0.1896, -0.1082, -0.0577,  0.2080,  0.0804,  0.1101],
        [ 0.0063,  0.9991,  0.1277,  0.0603, -0.0425,  0.0779, -0.0565,  0.0401,
          0.1197,  0.1425, -0.1812, -0.0352, -0.0751, -0.1607,  0.0748],
        [-0.0042,  0.1277,  0.8412, -0.0843, -0.0596, -0.0184,  0.0673,  0.0914,
         -0.0332,  0.0759,  0.0603,  0.0489, -0.0793, -0.1364, -0.1798],
        [-0.1425,  0.0603, -0.0843,  1.0906, -0.1012, -0.0196,  0.0162, -0.1699,
          0.1386,  0.1563, -0.1071, -0.0504,  0.0015,  0.1195, -0.0077],
        [ 0.0659, -0.0425, -0.0596, -0.1012,  1.1118,  0.0194, -0.0727, -0.1067,
         -0.0298, -0.0083, -0.0265, -0.1727,  0.0848,  0.0339, -0.0589],
        [ 0.2898,  0.0779, -0.0184, -0.0196,  0.0194,  1.4402, -0.0320,  0.0300,
         -0.0507, -0.1823, -0.0836,  0.0795, -0.0814,  0.2588, -0.0882],
        [ 0.0491, -0.0565,  0.0673,  0.0162, -0.0727, -0.0320,  0.9412,  0.1

In [96]:
).shaimport torch

k = 10
K = torch.randn((100, 100))
d = torch.randn((100, 15))
e = torch.eye(k, k)
A = torch.randn((100, k))
beta = (A.unsqueeze(1) - e).abs().sum(dim=2)
v = (beta.T @ K.abs() @ beta)
diag = v.diag().sqrt()
v = v/diag
v = v/diag.unsqueeze(1)
torch.triu(v, diagonal=1).sum()

tensor([[0.0000, 1.0008, 1.0008, 1.0004, 0.9999, 0.9998, 0.9999, 0.9995, 1.0000,
         1.0002],
        [0.0000, 0.0000, 1.0002, 0.9998, 0.9993, 0.9990, 0.9992, 0.9990, 0.9993,
         0.9995],
        [0.0000, 0.0000, 0.0000, 0.9996, 0.9990, 0.9988, 0.9990, 0.9988, 0.9993,
         0.9994],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.9995, 0.9994, 0.9996, 0.9991, 0.9997,
         0.9998],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9999, 1.0000, 0.9995, 1.0002,
         1.0002],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.9998, 1.0003,
         1.0004],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9994, 1.0001,
         1.0003],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0005,
         1.0008],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         1.0002],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [79]:
A

tensor([[-8.2120e-01, -4.1770e-01,  2.0557e+00,  1.5960e+00, -6.4530e-01,
          1.1327e-01,  4.7224e-01, -5.8765e-01, -1.5974e+00,  4.2410e-01],
        [ 7.8655e-01, -2.2920e-01,  1.7447e-02, -9.2780e-01, -1.2862e+00,
         -7.5273e-01,  9.5233e-02,  9.5742e-01, -1.5930e+00, -1.4159e+00],
        [ 2.0285e+00, -2.1471e-03, -1.7307e+00,  5.9737e-01,  8.2792e-02,
          6.9929e-01, -5.3195e-01,  8.8121e-01, -1.9412e+00, -2.0567e-01],
        [-3.1941e-01, -9.0237e-01,  5.3155e-01, -1.3626e-01, -4.2832e-01,
          8.0944e-03, -2.1539e+00, -3.8298e-01,  4.1261e-02, -1.1826e+00],
        [ 1.5831e-01, -4.9410e-01,  1.6792e-01,  4.4509e-01,  7.0470e-01,
         -1.1484e+00, -3.6358e-01,  8.1744e-01, -8.9144e-01,  5.9870e-01],
        [-2.2476e-01, -9.1493e-01,  1.7088e+00, -2.4432e-01,  1.3470e-01,
         -6.0519e-01, -7.6989e-01, -1.1399e+00,  5.8468e-01, -6.3527e-01],
        [-1.6631e+00,  1.3381e+00,  2.1632e-01,  9.5743e-01, -1.1679e+00,
         -4.9695e-01, -1.2276e+0

In [76]:
A.unsqueeze(1)-e

tensor([[[-1.8212e+00, -4.1770e-01,  2.0557e+00,  ..., -5.8765e-01,
          -1.5974e+00,  4.2410e-01],
         [-8.2120e-01, -1.4177e+00,  2.0557e+00,  ..., -5.8765e-01,
          -1.5974e+00,  4.2410e-01],
         [-8.2120e-01, -4.1770e-01,  1.0557e+00,  ..., -5.8765e-01,
          -1.5974e+00,  4.2410e-01],
         ...,
         [-8.2120e-01, -4.1770e-01,  2.0557e+00,  ..., -1.5876e+00,
          -1.5974e+00,  4.2410e-01],
         [-8.2120e-01, -4.1770e-01,  2.0557e+00,  ..., -5.8765e-01,
          -2.5974e+00,  4.2410e-01],
         [-8.2120e-01, -4.1770e-01,  2.0557e+00,  ..., -5.8765e-01,
          -1.5974e+00, -5.7590e-01]],

        [[-2.1345e-01, -2.2920e-01,  1.7447e-02,  ...,  9.5742e-01,
          -1.5930e+00, -1.4159e+00],
         [ 7.8655e-01, -1.2292e+00,  1.7447e-02,  ...,  9.5742e-01,
          -1.5930e+00, -1.4159e+00],
         [ 7.8655e-01, -2.2920e-01, -9.8255e-01,  ...,  9.5742e-01,
          -1.5930e+00, -1.4159e+00],
         ...,
         [ 7.8655e-01, -2