In [20]:
from torch.utils.data import Dataset, DataLoader

class Data(Dataset):
    def __init__(self):
        self.label = [1,2,3,4,5,6,7,8,9,10]
        
        
    def __getitem__(self, item):
        return self.label[item]
    
    def __len__(self):
        return 10
    
data = Data()
dataloader = DataLoader(data, shuffle=True, batch_size=10)

In [11]:
dataloader.dataset.label

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
for epoch in range(3):
    for batch, (labels) in enumerate(dataloader):
        print(labels)

tensor([ 6,  4,  1,  3, 10,  5,  9,  2,  8,  7])
tensor([ 3,  8, 10,  5,  9,  1,  4,  7,  6,  2])
tensor([ 2,  7,  1,  6,  9,  5,  3,  8,  4, 10])
