In [22]:
import faiss
import torch

d = torch.randn((100, 16)).numpy().astype('float32')
clus = faiss.Clustering(16, 10)
index = faiss.IndexFlatL2(16)
clus.train(d, index)

In [26]:
D.squeeze()

array([13.140303 , 13.045889 ,  5.0400853,  7.340887 ,  8.562076 ,
        9.953151 , 16.308582 ,  8.011513 ,  9.153503 ,  9.924595 ,
       15.094459 ,  6.5761967,  9.70984  ,  6.1749744, 12.93881  ,
        9.254005 ,  6.2600574,  5.8798265, 14.443888 , 19.547724 ,
        9.109628 , 11.274628 , 10.803336 , 10.305023 ,  6.801159 ,
       10.255474 , 10.817856 , 10.247408 ,  7.315468 , 22.511574 ,
       10.96105  , 17.383415 , 10.180412 , 13.446657 , 16.175508 ,
       17.16951  , 10.935697 , 12.894105 ,  5.314497 ,  8.358608 ,
        5.42647  ,  4.7651577,  7.994193 ,  9.804432 ,  7.2666593,
        8.4099045, 13.381054 ,  8.145706 , 10.615884 ,  6.6466074,
       15.823307 , 12.42525  , 13.968058 ,  4.695444 , 14.178653 ,
       13.022302 ,  5.492155 ,  6.042946 ,  5.443656 , 16.65215  ,
        5.0918884,  7.189308 , 11.445243 ,  9.016945 ,  5.168807 ,
       10.883819 ,  9.560805 , 15.082591 ,  8.899487 ,  9.916195 ,
       11.745177 ,  9.29768  , 12.887728 ,  4.348425 ,  9.6646

In [50]:
import numpy as np
d = np.linspace(1,200,200)
np.percentile(d, 90)

180.1

In [61]:
F.softmax?

In [68]:
import torch
import torch.nn as nn
import torch.nn.functional as F
d = torch.randn((10, 10)).numpy()
m = torch.tensor([0,1,1,2,3,4,5,5,6,7])
torch.tensor(d, dtype=torch.int8)

tensor([[ 0,  0,  0,  0,  0,  0,  1,  0,  0,  1],
        [ 0,  0, -1,  2,  0,  0,  0,  2, -1,  0],
        [ 0,  0,  0,  0,  0,  0,  1,  1,  0,  0],
        [ 0, -1, -2,  1,  2, -1, -1,  0, -1,  1],
        [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  0,  0, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0, -1, -1, -1,  0],
        [ 0, -1,  0,  0,  1,  0,  0,  0,  0, -1],
        [ 0, -1,  1, -1,  0,  1,  0,  0, -2,  0],
        [ 1, -1,  1,  0,  0,  1,  0,  0,  0,  0]], dtype=torch.int8)

In [23]:
D, I = index.search(d, 1)
labels = I.squeeze()
sim = D.squeeze()
DCluster = [[] for i in range(10)]
for i, d in enumerate(sim):
    DCluster[labels[i]].append(d)
    
    

In [43]:
faiss.vector_to_array(clus.centroids)

array([-3.20458949e-01,  5.77562332e-01, -2.25493550e-01, -1.16128780e-01,
       -3.41681719e-01,  9.97850597e-02,  7.02778280e-01,  6.22257702e-02,
        1.34024441e-01,  1.02988553e+00, -4.17268842e-01,  4.05852258e-01,
       -4.33494635e-02,  7.77275562e-01, -3.78510952e-02,  6.28338337e-01,
       -5.01980364e-01, -3.57066542e-01, -1.26428866e+00,  7.23235130e-01,
        2.67124563e-01,  2.63746411e-01,  9.09179866e-01, -2.95212865e-01,
        7.28178144e-01, -8.74979317e-01,  6.90106452e-01,  1.27310646e+00,
       -4.55206722e-01,  1.19418316e-01,  1.13865115e-01,  1.51149735e-01,
       -9.22076464e-01, -7.04618335e-01,  7.95852765e-03, -6.06903050e-04,
        7.52448812e-02, -6.01924181e-01, -2.62163818e-01,  6.75562739e-01,
       -7.26154387e-01,  1.39865249e-01, -8.27485859e-01, -7.29613304e-02,
       -3.37301582e-01, -5.20774901e-01,  2.86179841e-01, -9.97006595e-01,
        4.54185992e-01,  8.58679116e-01,  3.70432377e-01, -4.18429792e-01,
       -7.58820847e-02, -

In [40]:
import torch
d = torch.tensor(list(range(100))).view(10,10)
m = torch.tensor(list(range(10)))
d.sum(dim=1)

tensor([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [33]:

phi = []
for i, DC in enumerate(DCluster):
    phi.append((np.array(DC)**0.5).mean() / np.log(len(DC)+9)) 
    
phi

[1.0566130502877278,
 0.983011693395853,
 1.0324435451719887,
 1.1184902677919288,
 0.9830780046635533,
 1.0137792969221162,
 1.172485244472042,
 1.0330940223140876,
 1.0909075543413533,
 1.030889493582096]